### PR TITLE
Validate server URL when joining existing cluster

### PR DESCRIPTION
**Pull request by c3y1huang**
Checking for server URL availability can ensure invalid IP is discovered at an earlier stage instead of allowing for installation.

Screenshot-2021-02-18-14:17:47

Relate to https://github.com/rancher/harvester/issues/472

### CODE REVIEW

**Comment by gitlawr** [comment]
A 200 from K3s health check endpoint(https://1.2.3.4:6443/ping) would be a better option so that we don't accept arbitrary responses.

**Comment by gitlawr** [comment]
A 200 from K3s health check endpoint(https://1.2.3.4:6443/ping) would be a better option so that we don't accept arbitrary responses.

**Comment by gitlawr** [comment]
Can we use a spinner as we did for ssh keys?

**Comment by c3y1huang** [comment]
@gitlawr thanks! I've made some changes:
- check endpoint(https://1.2.3.4:6443/ping
- use spinner

**Review by gitlawr — APPROVED** [review]
LGTM

**Pull request merged**
